export const campaignsData =[
    {
        id:1,
        campaigns:'GGD MadeGuy Unisex Belt',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:2,
        campaigns:'GGD MadeGuy Unisex Belt | SP',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:3,
        campaigns:'GGD MadeGuy Unisex Belt |MP',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:4,
        campaigns:'GGD MadeGuy Unisex Belt | HHS',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:5,
        campaigns:'GGD MadeGuy Unisex Belt |LKG',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:6,
        campaigns:'GGD MadeGuy Unisex Belt | HKJ',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:7,
        campaigns:'GGD MadeGuy Unisex Belt',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:8,
        campaigns:'GGD MadeGuy Unisex Belt',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:9,
        campaigns:'GGD MadeGuy Unisex Belt',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:10,
        campaigns:'GGD MadeGuy Unisex Belt',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:11,
        campaigns:'GGD MadeGuy Unisex Belt | HJ',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
    {
        id:12,
        campaigns:'GGD MadeGuy Unisex Belt | JKY',
        status:'Paused',
        type:'Sponsored Display',
        target:'Manual targeting',
        startDate:'May 4,2022',
        EndDate:'No end Date',
        budget:'500.00',
        budgetType:'Daily',
        costType:'VCPM',
        top:'9085'
    },
]